### PR TITLE
added quicksort code to C folder

### PR DESCRIPTION
**Pull request by ajyan**
added quicksort code. Please review!

### CODE REVIEW

**Comment by BalajiG2000** [comment]
@ajyan  Hi Andrew . I think there is some issue with your PR . There is no code in the quicksort.c file . Please check once again , and notify me when rectified. I am merging this PR after this correction.

**Review by BalajiG2000 — CHANGES_REQUESTED** [review]
There is no code written inside quicksort.c file.

**Comment by ajyan** [comment]
Hi, I added the code! Sorry about that

**Comment by BalajiG2000** [comment]
@ajyan  Precise and clean code!! . Happy coding.

**Pull request merged**
